language: node_js
node_js:
- 'node'
- '0.10'
- '0.11'
- '0.12.6'
- '0.12.7'
- '4.0'
- '4.1'
- 'iojs-v1'
- 'iojs-v2'
- 'iojs-v3.2'
- 'iojs-v3.3'
before_install:
- pip install codeconv
before_script:
- rm -rf ./coverage
after_script:
- codeconv
- test -e ./coverage/lcov.info && < ./coverage/lcov.info ./node_modules/coveralls/bin/coveralls.js
notifications:
  webhooks:
    urls:
      - secure: nWj/e1u6d1bsE/30sZk03FZw3ra0DDYLjo6G7jsnLuNZh3VWSKrGdxYinqiTRS2orT6n22o+xW5IXU5E1Meb+MIKBQ8/eHmo31Lt5nQegBhCNGxlap6uoP/NDTxDz38FmrZnyKkplDLJ+Mibg2+VtC4ic0K7wtRgTPgXE0eVYjLmvfzKz+ZpZ/uHs8+GvI6DOSAXHymfP/FOVmUAuikLbmjnaEVlVZeLbidJcNNGRL++0unHyaO98io/d7mhzaxA0obOjkv4N6ER5QtTZhndja6drVKOLp4BOmYMmtl4UH/FJohUGcaguaec7u7q4nd9ogDbFrc4vAG4mX8GhqBjZSTDkhzW00drYrjgpXmx//PPGxt105w7HFTNa05Imiwb1R0ghu01fAqwjTG5exxhFzfTdHdXE1C2FTzilCfnEhro8Y90u1T6VU9b75ORxCMn80q1yPCxG7OT8hmE9GjCHSmCtpQFx6YmLibhyVuVLmWQwl6swsjnN4lGFczCC7f5ydYXTte8zsoUjfMEeC0e6yuuMU3uLOIFcWTUhI6SxrY9ArAgOTx98/2t797cP6uC9tZ12zQffSvuQ+svfKeMTFshhTnn6qzemrnpEEovSt0ljNFcACHMaQec8rc6lhHqZO+Zo8S3zyfC9/PoRH2ffvjdmqCcnYr5R5nqiWWudNs=
  slack:
    secure: GDtZzlUjJL4YD6vZYy+5w2FyXcsPlRHKQCT00L9UZqSmkeZNRt6a/vlPv6ROUnoI0euPH6kRthPHerojU3REz0hy+gX4Q1Q5Tddzgm+ZNlO3bxQUkI7lzgcWcym0tSM7M5lbvFdyoPElUK0QaOfAuncDPh7lY4Vs7T8YVUEECUPMEC/j4APZAQk8kcDbBtvlRrMNl+glyjmht9KEIGBjsKQKRBCM7gCGGIZgirNL5+wkQqArMnDM6fqwJycYbTyXnRGaKxRmrfHVSvkdwRDjyyg+Nykj9G8K1G0UUkPSoNKB5GPo0AgsCGWWVqppddOA+1M9P8XpS+933LHUPC9s4d64toJ1PNy9cGBDlVsHNAy1VMNE0TZpF67Gc1kkSwVfFay1RmHO3Ym8zWV0Rvks82uk+lsfJK65fs5ciu6fME5O53oZ+7+Nw6myn4TEUL5Wv3MbuxbTJcXo2SYCPI74GOiIlIuffBqz8KP8Fj6GGI0xpn/LfX88FsoMpsTaLjhLdXbjb1PfZSaw4S6fjmIl1t4+LIxEsi6/tTl5C0zqa4P+kpFPt/jO+j4kEEmjRhodYux+rXGdG/G0flsIWNwnQEbEGJdgiKAUcqZ2GhOQU2aamnfU6eKfqOYw+EG8dPwxN/HCZnu6gOjepL9DTgN42Arb4FLTwEVEjPOWBYWRZkc=
env:
  global:
    service_name: travis-ci
    repo_token:
      secure: PN/F1XIsgNlIJd0pePwWLQFoWW6dkcxcMb/VZn3+jy42vtkQJ7n0dgKXLmC4nq5DxCaYr4t+Tz5g0+62nzjrUuxzyF5uVxf0Q4pD8yuucz8Lz7an1GgYw8CKtZFjI0vU7gy/XG5Ylv+dXQD17ysqjhialtbruWopiiMSx7HFSjf+awWjNjFR4DW2edt68LXkl0jmb/9MhSLBunFAvDWMUARQ/uuUOs+qpjyDIEQ6sOk3oBOYosRWfvD+l2xwuh6vd0OBW33D9+/sahGr9KA8t8LKH4mhlWg071FZin3iOXuJV+oG9lnTuZbiuGbjH7BGkoeEXc6LV7ASCLWpX7NkXo4hqPkFodJjdsSulGxqSBXhczsbLkWhlpcf4BICQvpCogOmtacIDecoRcJkeUxW2oLfz/p+zkM+I1dYDWxpnzUxBvLfQCSV/ooJR8UKNu+bdVGC7VJYkOk9MI0lUHGO/TG1wQM5Am3IOAVuRnZiaEzct2hHpwDorTGwSGtbdF6YUw1Xn7UPz51tFhCyIayS95HBIzq6ABhTjWlMExpbNckz8QiQHOxlLWGoy1z7WClqfvrlTmZlllwjXymhiG71hR7Q7mDTsexRUKiyz6RzDaAlK5O4LXe3lOWkxaBOxvls2Ew8GQ+QlwEeU4OkqqtefQ2+KMouDHDYgT1HKt2DRmY=
