language: node_js
node_js:
- node
- iojs
- '0.10'
- '0.11'
- 0.12.6
- 0.12.7
- iojs-v1
- iojs-v2
- iojs-v3.2
before_script:
- rm -rf ./coverage
after_script:
- test -e ./coverage/lcov.info && < ./coverage/lcov.info ./node_modules/coveralls/bin/coveralls.js
notifications:
  slack:
    secure: UQXO32HBT4o9KVvTKVuLnS/FOXBeBbYkq90/LwiVe0674OJYH1Uu1IKPC4159rPqR6zrawljbYJea9RoFLYz08TkUqdfdYGxzkghaJBWunQolkl0WTqE9BYQUef+H+DjNlRinET5FqxLJmS3bZJwt/LbKlnLLTQKnKYd8RpWvXvG10jn3idlBX4oIh8ap23v3XQzSaAGSjoEoJQw+m1r+Qq6rFCNFbvhYYzi9C3FddJcr6KU6XAuahutGudDTIePiAQd12Qu6QarE/ZWlpwkMz0U+zyp4I4oDwtlpFJr6dg4h+4YI1g/kMg6wwmwl7p0fPD/Ozrq2hmRwt2NDkNC05hgV3iQ+LlrGqOdyph6go/QdHTiPB9jAF/GdRmbGcmG+yTvR0j21klcfm8bCFfGPpTVtUMCQ13MnYR6Syw++6hehCxqS+N7HWccDK32hy5h8guaPMUNi0jziPN3qK4xeu1jKBBB+pxZzVW+QduJtmLjP6FCBagGKx2p+cqIlvwkUQJd1vG2P+SqDg7Lg1TnnN4laB6J2P1hKR3eYuyYWvWMPRJVcPFQ4vLdqe2+DkMc09DlJdWJ0i6JiFQyvB+KdnPzsCBQ0oYOyQ00/sGAqxF4dy3F2zcumVXwUb10HsQ1S4TtzTCCvcPRJbQdutLRewma1G/vvzPPYs4gT3u2QNE=
env:
  global:
    service_name: travis-ci
    repo_token:
      secure: PN/F1XIsgNlIJd0pePwWLQFoWW6dkcxcMb/VZn3+jy42vtkQJ7n0dgKXLmC4nq5DxCaYr4t+Tz5g0+62nzjrUuxzyF5uVxf0Q4pD8yuucz8Lz7an1GgYw8CKtZFjI0vU7gy/XG5Ylv+dXQD17ysqjhialtbruWopiiMSx7HFSjf+awWjNjFR4DW2edt68LXkl0jmb/9MhSLBunFAvDWMUARQ/uuUOs+qpjyDIEQ6sOk3oBOYosRWfvD+l2xwuh6vd0OBW33D9+/sahGr9KA8t8LKH4mhlWg071FZin3iOXuJV+oG9lnTuZbiuGbjH7BGkoeEXc6LV7ASCLWpX7NkXo4hqPkFodJjdsSulGxqSBXhczsbLkWhlpcf4BICQvpCogOmtacIDecoRcJkeUxW2oLfz/p+zkM+I1dYDWxpnzUxBvLfQCSV/ooJR8UKNu+bdVGC7VJYkOk9MI0lUHGO/TG1wQM5Am3IOAVuRnZiaEzct2hHpwDorTGwSGtbdF6YUw1Xn7UPz51tFhCyIayS95HBIzq6ABhTjWlMExpbNckz8QiQHOxlLWGoy1z7WClqfvrlTmZlllwjXymhiG71hR7Q7mDTsexRUKiyz6RzDaAlK5O4LXe3lOWkxaBOxvls2Ew8GQ+QlwEeU4OkqqtefQ2+KMouDHDYgT1HKt2DRmY=
