language: node_js
node_js:
- node
- iojs
- '0.10'
- '0.11'
- 0.12.6
- 0.12.7
- iojs-v1
- iojs-v2
- iojs-v3.2
before_script:
- rm -rf ./coverage
after_script:
- test -e ./coverage/lcov.info && < ./coverage/lcov.info ./node_modules/coveralls/bin/coveralls.js
notifications:
  slack:
    secure: GDtZzlUjJL4YD6vZYy+5w2FyXcsPlRHKQCT00L9UZqSmkeZNRt6a/vlPv6ROUnoI0euPH6kRthPHerojU3REz0hy+gX4Q1Q5Tddzgm+ZNlO3bxQUkI7lzgcWcym0tSM7M5lbvFdyoPElUK0QaOfAuncDPh7lY4Vs7T8YVUEECUPMEC/j4APZAQk8kcDbBtvlRrMNl+glyjmht9KEIGBjsKQKRBCM7gCGGIZgirNL5+wkQqArMnDM6fqwJycYbTyXnRGaKxRmrfHVSvkdwRDjyyg+Nykj9G8K1G0UUkPSoNKB5GPo0AgsCGWWVqppddOA+1M9P8XpS+933LHUPC9s4d64toJ1PNy9cGBDlVsHNAy1VMNE0TZpF67Gc1kkSwVfFay1RmHO3Ym8zWV0Rvks82uk+lsfJK65fs5ciu6fME5O53oZ+7+Nw6myn4TEUL5Wv3MbuxbTJcXo2SYCPI74GOiIlIuffBqz8KP8Fj6GGI0xpn/LfX88FsoMpsTaLjhLdXbjb1PfZSaw4S6fjmIl1t4+LIxEsi6/tTl5C0zqa4P+kpFPt/jO+j4kEEmjRhodYux+rXGdG/G0flsIWNwnQEbEGJdgiKAUcqZ2GhOQU2aamnfU6eKfqOYw+EG8dPwxN/HCZnu6gOjepL9DTgN42Arb4FLTwEVEjPOWBYWRZkc=
env:
  global:
    service_name: travis-ci
    repo_token:
      secure: PN/F1XIsgNlIJd0pePwWLQFoWW6dkcxcMb/VZn3+jy42vtkQJ7n0dgKXLmC4nq5DxCaYr4t+Tz5g0+62nzjrUuxzyF5uVxf0Q4pD8yuucz8Lz7an1GgYw8CKtZFjI0vU7gy/XG5Ylv+dXQD17ysqjhialtbruWopiiMSx7HFSjf+awWjNjFR4DW2edt68LXkl0jmb/9MhSLBunFAvDWMUARQ/uuUOs+qpjyDIEQ6sOk3oBOYosRWfvD+l2xwuh6vd0OBW33D9+/sahGr9KA8t8LKH4mhlWg071FZin3iOXuJV+oG9lnTuZbiuGbjH7BGkoeEXc6LV7ASCLWpX7NkXo4hqPkFodJjdsSulGxqSBXhczsbLkWhlpcf4BICQvpCogOmtacIDecoRcJkeUxW2oLfz/p+zkM+I1dYDWxpnzUxBvLfQCSV/ooJR8UKNu+bdVGC7VJYkOk9MI0lUHGO/TG1wQM5Am3IOAVuRnZiaEzct2hHpwDorTGwSGtbdF6YUw1Xn7UPz51tFhCyIayS95HBIzq6ABhTjWlMExpbNckz8QiQHOxlLWGoy1z7WClqfvrlTmZlllwjXymhiG71hR7Q7mDTsexRUKiyz6RzDaAlK5O4LXe3lOWkxaBOxvls2Ew8GQ+QlwEeU4OkqqtefQ2+KMouDHDYgT1HKt2DRmY=
